export enum ActionType {
  CREATE_TASK = 'CREATE_TASK',
  UPDATE_TASK = 'UPDATE_TASK',
  DELETE_TASK = 'DELETE_TASK',
  MARK_COMPLETE = 'MARK_COMPLETE',
  LIST_TASKS = 'LIST_TASKS',
  INVALID_COMMAND = 'INVALID_COMMAND',
}

